#python try-catch exception
'''
 try catch actually checks code and run
 if any error occurs it shows error as exception and also handles it.
'''

try:
	
	number = int(input("Enter a number "))
	print(number)
except:
	print("Invalid Input")	

